python3 Blue_AI_Trainer.py --drop 0
python3 Blue_AI_Trainer.py --drop 1
python3 Blue_AI_Trainer.py --drop 2
python3 Blue_AI_Trainer.py --drop 3
python3 Blue_AI_Trainer.py --drop 4
python3 Blue_AI_Trainer.py --drop 5
python3 Blue_AI_Trainer.py --drop 6
python3 Blue_AI_Trainer.py --drop 7
python3 Blue_AI_Trainer.py --drop 8
python3 Blue_AI_Trainer.py --drop 9
python3 Blue_AI_Trainer.py --drop 10
python3 Blue_AI_Trainer.py --drop 11
python3 Blue_AI_Trainer.py --drop 12
python3 Blue_AI_Trainer.py --drop 13
python3 Blue_AI_Trainer.py --drop 14
python3 Blue_AI_Trainer.py --drop 15
python3 Blue_AI_Trainer.py --drop 16
python3 Blue_AI_Trainer.py --drop 17
python3 Blue_AI_Trainer.py --drop 18
python3 Blue_AI_Trainer.py --drop 19
python3 Blue_AI_Trainer.py --drop 20
python3 Blue_AI_Trainer.py --drop 21
python3 Blue_AI_Trainer.py --drop 22
python3 Blue_AI_Trainer.py --drop 23
python3 Blue_AI_Trainer.py --drop 24
python3 Blue_AI_Trainer.py --drop 25
python3 Blue_AI_Trainer.py --drop 26
python3 Blue_AI_Trainer.py --drop 27
python3 Blue_AI_Trainer.py --drop 28
python3 Blue_AI_Trainer.py --drop 29
python3 Blue_AI_Trainer.py --drop 30
python3 Blue_AI_Trainer.py --drop 31
python3 Blue_AI_Trainer.py --drop 32
python3 Blue_AI_Trainer.py --drop 33
python3 Blue_AI_Trainer.py --drop 34
python3 Blue_AI_Trainer.py --drop 35
python3 Blue_AI_Trainer.py --drop 36
python3 Blue_AI_Trainer.py --drop 37
python3 Blue_AI_Trainer.py --drop 38
python3 Blue_AI_Trainer.py --drop 39
python3 Blue_AI_Trainer.py --drop 40
python3 Blue_AI_Trainer.py --drop 41
python3 Blue_AI_Trainer.py --drop 42
python3 Blue_AI_Trainer.py --drop 43
python3 Blue_AI_Trainer.py --drop 44
python3 Blue_AI_Trainer.py --drop 45
python3 Blue_AI_Trainer.py --drop 46
python3 Blue_AI_Trainer.py --drop 47
python3 Blue_AI_Trainer.py --drop 48
python3 Blue_AI_Trainer.py --drop 49
python3 Blue_AI_Trainer.py --drop 50
python3 Blue_AI_Trainer.py --drop 51
python3 Blue_AI_Trainer.py --drop 52
python3 Blue_AI_Trainer.py --drop 53
python3 Blue_AI_Trainer.py --drop 54
python3 Blue_AI_Trainer.py --drop 55
python3 Blue_AI_Trainer.py --drop 56
python3 Blue_AI_Trainer.py --drop 57
python3 Blue_AI_Trainer.py --drop 58
python3 Blue_AI_Trainer.py --drop 59
python3 Blue_AI_Trainer.py --drop 60
python3 Blue_AI_Trainer.py --drop 61
python3 Blue_AI_Trainer.py --drop 62
python3 Blue_AI_Trainer.py --drop 63
python3 Blue_AI_Trainer.py --drop 64
python3 Blue_AI_Trainer.py --drop 65
python3 Blue_AI_Trainer.py --drop 66
python3 Blue_AI_Trainer.py --drop 67
python3 Blue_AI_Trainer.py --drop 68
python3 Blue_AI_Trainer.py --drop 69
python3 Blue_AI_Trainer.py --drop 70
python3 Blue_AI_Trainer.py --drop 71
python3 Blue_AI_Trainer.py --drop 72
python3 Blue_AI_Trainer.py --drop 73
python3 Blue_AI_Trainer.py --drop 74
python3 Blue_AI_Trainer.py --drop 75
python3 Blue_AI_Trainer.py --drop 76
python3 Blue_AI_Trainer.py --drop 77
python3 Blue_AI_Trainer.py --drop 78
python3 Blue_AI_Trainer.py --drop 79
python3 Blue_AI_Trainer.py --drop 80
python3 Blue_AI_Trainer.py --drop 81
python3 Blue_AI_Trainer.py --drop 82
python3 Blue_AI_Trainer.py --drop 83
python3 Blue_AI_Trainer.py --drop 84
python3 Blue_AI_Trainer.py --drop 85
python3 Blue_AI_Trainer.py --drop 86
python3 Blue_AI_Trainer.py --drop 87
python3 Blue_AI_Trainer.py --drop 88
python3 Blue_AI_Trainer.py --drop 89
python3 Blue_AI_Trainer.py --drop 90
python3 Blue_AI_Trainer.py --drop 91
python3 Blue_AI_Trainer.py --drop 92
python3 Blue_AI_Trainer.py --drop 93
python3 Blue_AI_Trainer.py --drop 94
python3 Blue_AI_Trainer.py --drop 95
python3 Blue_AI_Trainer.py --drop 96
python3 Blue_AI_Trainer.py --drop 97
python3 Blue_AI_Trainer.py --drop 98
python3 Blue_AI_Trainer.py --drop 99
python3 Blue_AI_Trainer.py --drop 100
 